# Set the Ctrl+B prefix key explicitly
unbind C-b
set -g prefix C-b
bind C-b send-prefix # Send the Ctrl+B prefix to apps when clicked twice

set -g mouse on
set -g default-terminal "screen-256color"

# Explicitly set the base index and pane base index to 0
set -g base-index 0
setw -g pane-base-index 0

# Set pane border colours
set -g pane-border-style "fg=colour245"
set -g pane-active-border-style "fg=colour33"

# Set 256 colour support
set -g default-terminal "tmux-256color"
