[General]
appdatadir=/home/abdul/.config/Meltytech/
askUpgradeAutomatic=false
backupPeriod=0
checkUpgradeAutomatic=false
clearRecent=false
convertAdvanced=true
exportRangeMarkers=false
flatpakWrappers=false
imageDuration=15
jobPriority=normal
language=en_GB
noupgrade=true
openPath=/home/abdul/
opengl=0
processingMode=0
projectsFolder=/home/abdul/
savePath=/home/abdul/
showConvertClipDialog=true
theme=dark
timeFormat=1
titleBars=true
toolBar=true
undoLimit=300
warnLowMemory=true