[General]
appdatadir=/home/abdul/.config/Meltytech/
askUpgradeAutomatic=false
backupPeriod=0
checkUpgradeAutomatic=false
clearRecent=false
convertAdvanced=true
exportRangeMarkers=false
flatpakWrappers=false
imageDuration=15
jobPriority=normal
language=en_GB
noupgrade=true
openPath=/home/abdul/
opengl=0
processingMode=0
projectsFolder=/home/abdul/
savePath=/home/abdul/
showConvertClipDialog=true
theme=dark
timeFormat=1
titleBars=true
toolBar=true
undoLimit=300
warnLowMemory=true

[encode]
advanced=false
freeSpaceCheck=true
hardwareDecoder=true
path=/home/abdul/
useHardware=true

[files]
foldersOpen=true
viewMode=detailed

[filter]
askOutput=true
audioInCurve=1
audioOutCurve=1

[keyframes]
dragScrub=false

[markers]
color=green
columns/color=true
columns/duration=true
columns/end=true
columns/start=true
columns/text=true
sortColumn=4
sortOrder=0