local config_path = vim.fn.stdpath("config") .. "/config/"

dofile(config_path .. "dependencies.lua")
dofile(config_path .. "autopairs.lua")
dofile(config_path .. "comment.lua")
dofile(config_path .. "indent-blankline.lua")
dofile(config_path .. "lualine.lua")
dofile(config_path .. "mason.lua")
dofile(config_path .. "neo-tree.lua")
dofile(config_path .. "neominimap.lua")
dofile(config_path .. "nvim-surround.lua")
dofile(config_path .. "nvim-treesitter.lua")
dofile(config_path .. "nvimpager.lua")
dofile(config_path .. "quickui.lua")
dofile(config_path .. "render-markdown.lua")
dofile(config_path .. "settings.lua")
vim.cmd("colorscheme colour-scheme")
