# Code syntax highlighting inside superfile
code_syntax_highlight = "monokai"

# Border
file_panel_border = "#555555"
sidebar_border = "#555555"
footer_border = "#555555"

# Border Active
file_panel_border_active = "#00FF00"
sidebar_border_active = "#00FF00"
footer_border_active = "#00FF00"
modal_border_active = "#00FF00"

# Background
full_screen_bg = "#000000"
file_panel_bg = "#000000"
sidebar_bg = "#000000"
footer_bg = "#000000"
modal_bg = "#000000"

# Foreground
full_screen_fg = "#00FF00"
file_panel_fg = "#00FF00"
sidebar_fg = "#00FF00"
footer_fg = "#00FF00"
modal_fg = "#00FF00"

# Special Color
cursor = "#00FF00"
correct = "#00FF00"
error = "#FF0000"
hint = "#008855"
cancel = "#FF0000"
gradient_color = ["#000000", "#000000"]

# File Panel Special Items
file_panel_top_directory_icon = "#AAFF00"
file_panel_top_path = "#AAFF00"
file_panel_item_selected_fg = "#000000"
file_panel_item_selected_bg = "#00FF00"

# Sidebar Special Items
sidebar_title = "#AAFF00"
sidebar_item_selected_fg = "#000000"
sidebar_item_selected_bg = "#00FF00"
sidebar_divider = "#555555"

# Modal Special Items
modal_cancel_fg = "#FF0000"
modal_cancel_bg = "#880000"
modal_confirm_fg = "#00FF00"
modal_confirm_bg = "#007700"

# Help Menu
help_menu_hotkey = "#AAFF00"
help_menu_title = "#00FF00"