[Icon Theme]
Name=custom-icon-theme
Comment=Custom icon theme for LabWC and standalone applications
Directories=apps/16,apps/22,apps/24,apps/32,apps/48,apps/64,apps/128,apps/256,apps/512,mimetypes/16,mimetypes/22,mimetypes/24,mimetypes/32,mimetypes/48,mimetypes/64,mimetypes/128,actions/16,actions/22,actions/24,actions/32,actions/48,devices/16,devices/22,devices/24,devices/32,devices/48,devices/64,emblems/16,emblems/22,emblems/24,emblems/32,emblems/48,places/16,places/22,places/24,places/32,places/48,places/64,status/16,status/22,status/24,status/32,status/48

[apps/16]
Size=16
Context=Apps
Type=Threshold

[apps/22]
Size=22
Context=Apps
Type=Threshold

[apps/24]
Size=24
Context=Apps
Type=Threshold

[apps/32]
Size=32
Context=Apps
Type=Threshold

[apps/48]
Size=48
Context=Apps
Type=Threshold

[apps/64]
Size=64
Context=Apps
Type=Threshold

[apps/128]
Size=128
Context=Apps
Type=Threshold

[apps/256]
Size=256
Context=Apps
Type=Threshold

[apps/512]
Size=512
Context=Apps
Type=Threshold

[mimetypes/16]
Size=16
Context=MimeTypes
Type=Threshold

[mimetypes/22]
Size=22
Context=MimeTypes
Type=Threshold

[mimetypes/24]
Size=24
Context=MimeTypes
Type=Threshold

[mimetypes/32]
Size=32
Context=MimeTypes
Type=Threshold

[mimetypes/48]
Size=48
Context=MimeTypes
Type=Threshold

[mimetypes/64]
Size=64
Context=MimeTypes
Type=Threshold

[mimetypes/128]
Size=128
Context=MimeTypes
Type=Threshold

[actions/16]
Size=16
Context=Actions
Type=Threshold

[actions/22]
Size=22
Context=Actions
Type=Threshold

[actions/24]
Size=24
Context=Actions
Type=Threshold

[actions/32]
Size=32
Context=Actions
Type=Threshold

[actions/48]
Size=48
Context=Actions
Type=Threshold

[devices/16]
Size=16
Context=Devices
Type=Threshold

[devices/22]
Size=22
Context=Devices
Type=Threshold

[devices/24]
Size=24
Context=Devices
Type=Threshold

[devices/32]
Size=32
Context=Devices
Type=Threshold

[devices/48]
Size=48
Context=Devices
Type=Threshold

[devices/64]
Size=64
Context=Devices
Type=Threshold

[emblems/16]
Size=16
Context=Emblems
Type=Threshold

[emblems/22]
Size=22
Context=Emblems
Type=Threshold

[emblems/24]
Size=24
Context=Emblems
Type=Threshold

[emblems/32]
Size=32
Context=Emblems
Type=Threshold

[emblems/48]
Size=48
Context=Emblems
Type=Threshold

[places/16]
Size=16
Context=Places
Type=Threshold

[places/22]
Size=22
Context=Places
Type=Threshold

[places/24]
Size=24
Context=Places
Type=Threshold

[places/32]
Size=32
Context=Places
Type=Threshold

[places/48]
Size=48
Context=Places
Type=Threshold

[places/64]
Size=64
Context=Places
Type=Threshold

[status/16]
Size=16
Context=Status
Type=Threshold

[status/22]
Size=22
Context=Status
Type=Threshold

[status/24]
Size=24
Context=Status
Type=Threshold

[status/32]
Size=32
Context=Status
Type=Threshold

[status/48]
Size=48
Context=Status
Type=Threshold